// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contracts/record.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecordRequest struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                float32              `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	SensorId             string               `protobuf:"bytes,3,opt,name=sensorId,proto3" json:"sensorId,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecordRequest) Reset()         { *m = RecordRequest{} }
func (m *RecordRequest) String() string { return proto.CompactTextString(m) }
func (*RecordRequest) ProtoMessage()    {}
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45850a59bd4d4975, []int{0}
}

func (m *RecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordRequest.Unmarshal(m, b)
}
func (m *RecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordRequest.Marshal(b, m, deterministic)
}
func (m *RecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordRequest.Merge(m, src)
}
func (m *RecordRequest) XXX_Size() int {
	return xxx_messageInfo_RecordRequest.Size(m)
}
func (m *RecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecordRequest proto.InternalMessageInfo

func (m *RecordRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RecordRequest) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *RecordRequest) GetSensorId() string {
	if m != nil {
		return m.SensorId
	}
	return ""
}

func (m *RecordRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type RecordResponse struct {
	Record               *RecordRequest       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	SavedAt              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=savedAt,proto3" json:"savedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecordResponse) Reset()         { *m = RecordResponse{} }
func (m *RecordResponse) String() string { return proto.CompactTextString(m) }
func (*RecordResponse) ProtoMessage()    {}
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45850a59bd4d4975, []int{1}
}

func (m *RecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordResponse.Unmarshal(m, b)
}
func (m *RecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordResponse.Marshal(b, m, deterministic)
}
func (m *RecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordResponse.Merge(m, src)
}
func (m *RecordResponse) XXX_Size() int {
	return xxx_messageInfo_RecordResponse.Size(m)
}
func (m *RecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecordResponse proto.InternalMessageInfo

func (m *RecordResponse) GetRecord() *RecordRequest {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *RecordResponse) GetSavedAt() *timestamp.Timestamp {
	if m != nil {
		return m.SavedAt
	}
	return nil
}

type ListRecordsRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRecordsRequest) Reset()         { *m = ListRecordsRequest{} }
func (m *ListRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecordsRequest) ProtoMessage()    {}
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45850a59bd4d4975, []int{2}
}

func (m *ListRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecordsRequest.Unmarshal(m, b)
}
func (m *ListRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecordsRequest.Marshal(b, m, deterministic)
}
func (m *ListRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecordsRequest.Merge(m, src)
}
func (m *ListRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecordsRequest.Size(m)
}
func (m *ListRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecordsRequest proto.InternalMessageInfo

func (m *ListRecordsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*RecordRequest)(nil), "RecordRequest")
	proto.RegisterType((*RecordResponse)(nil), "RecordResponse")
	proto.RegisterType((*ListRecordsRequest)(nil), "ListRecordsRequest")
}

func init() {
	proto.RegisterFile("contracts/record.proto", fileDescriptor_45850a59bd4d4975)
}

var fileDescriptor_45850a59bd4d4975 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xbf, 0xcd, 0x67, 0xab, 0x9d, 0x6a, 0x85, 0xb5, 0x48, 0xc8, 0xc5, 0x92, 0x83, 0x14,
	0x0f, 0x1b, 0xa9, 0x82, 0x5e, 0xf5, 0x26, 0x78, 0xda, 0x7a, 0xf2, 0xb6, 0x4d, 0xc6, 0xb2, 0xd0,
	0x64, 0xe3, 0xce, 0x26, 0xe0, 0x6f, 0xf0, 0x4f, 0x0b, 0xbb, 0xae, 0x5a, 0x15, 0x3c, 0xbe, 0xc9,
	0x3b, 0xfb, 0x3c, 0x33, 0x70, 0x5c, 0x9a, 0xc6, 0x59, 0x55, 0x3a, 0x2a, 0x2c, 0x96, 0xc6, 0x56,
	0xa2, 0xb5, 0xc6, 0x99, 0xec, 0x64, 0x6d, 0xcc, 0x7a, 0x83, 0x85, 0x4f, 0xab, 0xee, 0xa9, 0x70,
	0xba, 0x46, 0x72, 0xaa, 0x6e, 0x43, 0x21, 0x7f, 0x65, 0x70, 0x20, 0xfd, 0x84, 0xc4, 0xe7, 0x0e,
	0xc9, 0xf1, 0x09, 0x24, 0xba, 0x4a, 0xd9, 0x8c, 0xcd, 0x47, 0x32, 0xd1, 0x15, 0x9f, 0xc2, 0xa0,
	0x57, 0x9b, 0x0e, 0xd3, 0x64, 0xc6, 0xe6, 0x89, 0x0c, 0x81, 0x67, 0xb0, 0x47, 0xd8, 0x90, 0xb1,
	0x77, 0x55, 0xfa, 0xdf, 0x77, 0x3f, 0x32, 0xbf, 0x86, 0x51, 0x69, 0x51, 0x39, 0xac, 0x6e, 0x5c,
	0xba, 0x33, 0x63, 0xf3, 0xf1, 0x22, 0x13, 0x41, 0x44, 0x44, 0x11, 0xf1, 0x10, 0x45, 0xe4, 0x67,
	0x39, 0x6f, 0x60, 0x12, 0x65, 0xa8, 0x35, 0x0d, 0x21, 0x3f, 0x85, 0x61, 0x58, 0xc8, 0x1b, 0x8d,
	0x17, 0x13, 0xb1, 0x65, 0x2b, 0xdf, 0xff, 0xf2, 0x4b, 0xd8, 0x25, 0xd5, 0x7b, 0x62, 0xf2, 0x27,
	0x31, 0x56, 0xf3, 0x33, 0xe0, 0xf7, 0x9a, 0x5c, 0x78, 0x92, 0xe2, 0x05, 0xa6, 0x30, 0xd8, 0xe8,
	0x5a, 0x3b, 0x8f, 0x1c, 0xc8, 0x10, 0x16, 0x2f, 0xf1, 0x50, 0x4b, 0xb4, 0xbd, 0x2e, 0x91, 0x17,
	0x00, 0x4b, 0xd5, 0x63, 0xf8, 0xc8, 0xbf, 0x89, 0x65, 0x87, 0x62, 0x7b, 0x93, 0xfc, 0x1f, 0xbf,
	0x82, 0xf1, 0x17, 0x1a, 0x3f, 0x12, 0x3f, 0xd9, 0xbf, 0x8c, 0x9d, 0xb3, 0xdb, 0xfd, 0x47, 0x10,
	0x05, 0x05, 0x2c, 0xad, 0x86, 0x7e, 0xa3, 0x8b, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x52,
	0xf9, 0x58, 0xf4, 0x01, 0x00, 0x00,
}
